# Generated by Django 3.0.2 on 2020-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='calendly_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
