# Generated by Django 3.0.2 on 2020-01-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slackuser_calendly_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='slack_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
