# Generated by Django 3.0.2 on 2020-02-01 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200125_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slack_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plan', models.CharField(choices=[('small', 'Standard'), ('medium', 'Business'), ('large', 'Enterprise')], max_length=16)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
