# Generated by Django 3.0.2 on 2020-02-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200201_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.Workspace'),
        ),
    ]
