# Generated by Django 3.0.2 on 2020-02-17 23:25

from django.db import migrations, models
import web.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200206_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='trial_end',
            field=models.DateField(default=web.core.models.set_trial_end),
        ),
    ]
