# Generated by Django 3.0.2 on 2020-03-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200308_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='core.SlackUser'),
        ),
    ]
