# Generated by Django 3.0.2 on 2020-03-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200319_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='is_installer',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
