# Generated by Django 3.0.2 on 2020-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200321_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='destination_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
