# Generated by Django 3.0.2 on 2020-03-28 18:30

from django.db import migrations, models


def add_user_count(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    for workspace in Workspace.objects.all():
        workspace.user_count = workspace.slackusers.count()
        workspace.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_webhook_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(add_user_count, migrations.RunPython.noop)
    ]
