# Generated by Django 3.0.2 on 2020-03-28 18:58

import logging
from django.db import migrations


logger = logging.getLogger(__name__)


def remove_extra_users(apps, schema_editor):
    SlackUser = apps.get_model('core', 'SlackUser')
    Workspace = apps.get_model('core', 'Workspace')

    for workspace in Workspace.objects.all():
        user_queryset = SlackUser.objects.filter(workspace=workspace, manager=True)
        if user_queryset.exists():
            SlackUser.objects.filter(workspace=workspace, manager=False).delete()
        else:
            logger.warning(f'Manual edit for Workspace {workspace}')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_workspace_user_count'),
    ]

    operations = [
        migrations.RunPython(remove_extra_users, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='slackuser',
            name='manager',
        ),
    ]
