# Generated by Django 3.0.2 on 2020-03-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200328_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackuser',
            name='manager',
        ),
    ]
