# Generated by Django 3.0.2 on 2020-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_slackuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='calendly_authtoken',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
