# Generated by Django 3.0.2 on 2020-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200401_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='calendly_authtoken',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='calendly_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
