# Generated by Django 3.0.2 on 2020-05-06 13:03
from calendly import Calendly
from django.db import migrations, models


def create_event_destination(apps, schema_editor):
    Webhook = apps.get_model('core', 'Webhook')

    for w in Webhook.objects.all():
        print(w.calendly_id, w.destination_id, w.event_id)
        print(w.user.calendly_authtoken)
        calendly = Calendly(w.user.calendly_authtoken)
        events = calendly.event_types()
        active_event_ids = [e['id'] for e in events['data'] if e['attributes']['active']]
        w.event_id = active_event_ids[0]
        w.save()
        for new_hook in active_event_ids[1:]:
            Webhook.objects.create(user=w.user, calendly_id=w.calendly_id, destination_id=w.destination_id, event_id=new_hook)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200429_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='event_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(create_event_destination, migrations.RunPython.noop)
    ]
