# Generated by Django 3.0.2 on 2020-05-10 11:06

from django.db import migrations, models


def make_event_ids_not_null(apps, schema_editor):
    Webhook = apps.get_model('core', 'Webhook')

    for w in Webhook.objects.all():
        if w.event_id is None:
            w.event_id = ''
            w.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_webhook_event_id'),
    ]

    operations = [
        migrations.RunPython(make_event_ids_not_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='webhook',
            name='event_id',
            field=models.CharField(max_length=64),
        ),
    ]
