# Generated by Django 3.0.2 on 2020-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_webhook_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_id',
            field=models.CharField(max_length=64),
        ),
    ]
