# Generated by Django 3.0.2 on 2020-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200510_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
