# Generated by Django 3.0.2 on 2020-05-10 14:39

from django.db import migrations, models
import django.db.models.deletion


def fill_events(apps, schema_editor):
    Webhook = apps.get_model('core', 'Webhook')
    Filter = apps.get_model('core', 'Filter')

    for w in Webhook.objects.all():
        Filter.objects.create(user=w.user, destination_id=w.destination_id, event_id=w.event_id)
        if Webhook.objects.filter(user=w.user).count() > 1:
            w.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_webhook_enabled'),
    ]

    operations = [
        migrations.RunPython(fill_events, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='webhook',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='webhook',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook', to='core.SlackUser'),
        )
    ]
