# Generated by Django 3.0.2 on 2020-05-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200510_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='core.SlackUser'),
        ),
    ]
