# Generated by Django 3.0.2 on 2020-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200521_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='calendly_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
