# Generated by Django 3.0.2 on 2020-06-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
